name: Trigger auto deployment for ghaapp-northcentralusstage

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'updateTestApp/**'
    - '.github/workflows/ghaapp-northcentralusstage-AutoDeployTrigger-cb170fb8-f6f9-4f0c-a2ed-60757a960da4.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cappsinttestregistryprivate.azurecr.io
          username: ${{ secrets.GHAAPPNORTHCENTRALUSSTAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.GHAAPPNORTHCENTRALUSSTAGE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cappsinttestregistryprivate.azurecr.io/ghaapp-northcentralusstage:${{ github.sha }}
          file: updateTestApp/Dockerfile
          context: updateTestApp/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GHAAPPNORTHCENTRALUSSTAGE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ghaapp-northcentralusstage -g workerapps-rg-xj --server cappsinttestregistryprivate.azurecr.io --username  ${{ secrets.GHAAPPNORTHCENTRALUSSTAGE_REGISTRY_USERNAME }} --password ${{ secrets.GHAAPPNORTHCENTRALUSSTAGE_REGISTRY_PASSWORD }}
            az containerapp update -n ghaapp-northcentralusstage -g workerapps-rg-xj --image cappsinttestregistryprivate.azurecr.io/ghaapp-northcentralusstage:${{ github.sha }}
